name: Run tests

on:
  # Trigger the workflow on push or pull request to master
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: run tests
      run: python3 -m unittest -v tests.test_telegram_events
